version: '2'
services:
  spark-master:
    extends:
      file: common-services.yml
      service: spark-master

  spark-slave1:
    extends:
      file: common-services.yml
      service: spark-slave
    container_name: slave1
    hostname: slave1
    environment:
       - "constraint:node==swarm-node-1"

  spark-slave2:
    extends:
      file: common-services.yml
      service: spark-slave
    container_name: slave2
    hostname: slave2
    environment:
      - "constraint:node==swarm-node-2"

  spark-slave3:
    extends:
      file: common-services.yml
      service: spark-slave
    container_name: slave3
    hostname: slave3
    environment:
      - "constraint:node==swarm-node-3"
